[licenses]
version = 2
allow = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unlicense",
    "Zlib",
    "Unicode-3.0",
    "GPL-3.0",
    "MPL-2.0",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
